name: P2P-TA
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pip=21.3.1
  - pip:
      - pandas==1.4.2
      - dash==2.3.1
      - dash_auth==1.4.1
      - networkx==2.7.1
      - numpy==1.21.5
      - openpyxl==3.0.9
      - plotly==5.6.0
      - dash-bootstrap-compontents==1.1.0
