name: cxc-summer-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pip=21.3.1
  - jupyterlab
  - ipykernel
  - pip:
      - pandas==1.4.1
      - openpyxl==3.0.9
      - PyYAML==6.0
      - matplotlib==3.4.3
      - seaborn==0.11.2
      - pyarrow==8.0.0
      - fastparquet==0.8.1
