name: P2P-TA
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - pip=21.3.1
  - pip:
      - dash-bootstrap-components==0.13.1
      - dash~=2.3.1
      - dash-auth==1.4.1
      - dnspython==1.16.0
      - gunicorn==20.1.0
      - matplotlib==3.4.3
      - networkx~=2.7.1
      - numpy~=1.21.5
      - pandas~=1.4.2
      - python-crontab==2.5.1
      - plotly~=5.6.0
      - entsoe-py
      - openpyxl
